bypass-blocks:
- '39'
- '40'
- '51'
- '59'
unprotectable-blocks:
- '54'
- '58'
- '61'
- '62'
unbreakable-blocks: []
hiding-mask-blocks:
- '1'
- '2'
- '3'
- '4'
- '5'
- '7'
- '12'
- '13'
- '17'
- '18'
- '20'
- '24'
- '35'
- '43'
- '45'
- '47'
- '48'
- '49'
- '53'
- '60'
- '67'
- '80'
- '81'
- '82'
- '87'
- '88'
- '89'
- '99'
- '100'
- '108'
- '109'
- '110'
- '123'
- '124'
- '125'
- '128'
- '134'
- '135'
- '136'
tool-items:
- 269
- 270
- 271
- 273
- 274
- 275
- 277
- 278
- 279
- 284
- 285
- 286
- 290
- 291
- 292
- 293
- 294
repairable-items:
- 256
- 257
- 258
- 259
- 267
- 268
- 269
- 270
- 271
- 272
- 273
- 274
- 275
- 276
- 277
- 278
- 279
- 283
- 284
- 285
- 286
- 290
- 291
- 292
- 293
- 294
- 298
- 299
- 300
- 301
- 302
- 303
- 304
- 305
- 306
- 307
- 308
- 309
- 310
- 311
- 312
- 313
- 314
- 315
- 316
- 317
- 359
force-field-blocks:
- title: Big Protection
  block: 41
  radius: 9
  custom-height: 19
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-explosions: true
  prevent-unprotectable: false
  prevent-enderman-destroy: true
  prevent-flow: true
  welcome-message: true
  farewell-message: true
  visualize-on-rightclick: true
  visualize-on-place: true
  rentable: true
  shareable: true
  buyable: true
  price: 0.1
  refund: 0.1
  cuboid: true
  dynmap-area: true
  dynmap-marker: true
- title: Small Protection
  block: 42
  radius: 2
  custom-height: 5
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-explosions: true
  prevent-unprotectable: false
  prevent-enderman-destroy: true
  prevent-flow: true
  welcome-message: false
  farewell-message: false
  price: 0.1
  refund: 0.1
  cuboid: false
  dynmap-area: true
  dynmap-marker: true
- title: Creture Control
  block: 22
  radius: 7
  custom-height: 15
  prevent-mob-spawn: true
  prevent-animal-spawn: true
  protect-animals: true
  protect-mobs: false
  protect-villagers: true
  protect-crops: true
  cuboid: true
  price: 0.1
  refund: 0.1
log:
  translocation: true
  rollback: true
  fire: true
  entry: true
  place: true
  use: true
  pvp: true
  destroy: true
  destroy-area: false
  place-area: false
  unprotectable: true
  bypass-pvp: true
  bypass-delete: true
  bypass-place: true
  bypass-destroy: true
  conflict-place: true
  rents-and-purchases: true
notify:
  translocation: true
  rollback: true
  place: true
  destroy: true
  bypass-unprotectable: true
  bypass-pvp: true
  bypass-place: true
  bypass-destroy: true
  fly-zones: true
warn:
  instant-heal: true
  slow-heal: true
  slow-damage: true
  slow-feeding: true
  slow-repair: true
  fast-damage: true
  air: true
  fire: true
  entry: true
  place: true
  use: true
  pvp: true
  destroy: true
  destroy-area: true
  unprotectable: true
  launch: true
  cannon: true
  mine: true
settings:
  prevent-removal-if-player-in-field: true
  disable-simpleclans-hook: false
  max-size-translocation: 100000
  max-size-translocation-for-redstone: 1000
  version: 12
  prevent-place-everywhere:
  - creative_world
  prevent-destroy-everywhere:
  - creative_world
  show-default-welcome-farewell-messages: true
  sneak-to-place-field: false
  sneak-to-place-normal-block: true
  disable-ground-info: true
  global-field-limit: 1000000
  no-refund-for-fields: false
  public-block-details: false
  drop-on-delete: true
  disable-alerts-for-admins: true
  disable-bypass-alerts-for-admins: false
  off-by-default: false
  lines-per-page: 12
  log-to-hawkeye: false
  show-debug-info: false
  blacklisted-worlds:
  - creative_world
  auto-allow-clan-on-fields: true
  check-once-per-block-on-move: false
  use-blockids-in-snitches: false
  fence-max-depth: 50
cuboid:
  defining-blocktype: 49
  visualization-blocktype: 20
cleanup:
  player-inactivity-purge-days: 30
  purge-banned-players: true
saving:
  frequency-seconds: 15
  max-records-per-snitch: 50
visualization:
  frame-block-type: 20
  block-type: 20
  seconds: 60
  new-dotted-style: true
  end-on-player-move: false
  mark-block-type: 49
  default-density: 8
  blocks-to-send: 100
  max-fields-to-visualize-at-once: 5
  ticks-between-sends: 10
grief-revert:
  min-interval-secs: 30
  black-list:
  - '92'
mysql:
  enable: true
  host: localhost
  port: 3306
  database: minecraft
  username: minecraft
  password: minecraft
