# MobArena v0.96.4 - Config-file
# Read the Wiki for details on how to set up this file: http://goo.gl/F5TTc
# Note: You -must- use spaces instead of tabs!
global-settings:
  enabled: true
  allowed-commands: /list, /pl
  update-notification: true
classes:
  Knight:
    items: diamond_sword, potion:8197:3
    armor: 306,307,308,309
  Tank:
    items: iron_sword, potion:8229:2
    armor: 310,311,312,313
  Archer:
    items: wood_sword, bow, arrow:256, potion:8197:3, bone
    armor: 298,299,300,301
  Chemist:
    items: stone_sword, potion:16428:30, potion:16388:8, potion:16389:20, potion:8197:3, potion:8226:1
    armor: 314,315,316,317
  Oddjob:
    items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:8197:3
    armor: 298,299,300,301
arenas:
  mazenta-01:
    settings:
      world: world
      enabled: true
      protect: true
      entry-fee: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      hellhounds: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      auto-respawn: true
      share-items-in-arena: true
      min-players: 0
      max-players: 0
      max-join-distance: 0
      first-wave-delay: 5
      wave-interval: 15
      final-wave: 0
      monster-limit: 100
      monster-exp: false
      keep-exp: true
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      global-join-announce: false
      global-end-announce: false
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            wolves: 10
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered-creepers: 10
            zombie-pigmen: 10
            angry-wolves: 10
            blazes: 10
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          health: high
          abilities: arrows, root-target, throw-nearby
    rewards:
      waves:
        every:
          '3': feather, bone, stick
          '5': dirt:4, gravel:4, stone:4
          '10': iron_ingot:10, gold_ingot:8
        after:
          '7': minecart, storage_minecart, powered_minecart
          '13': iron_sword, iron_pickaxe, iron_spade
          '16': diamond_sword
    coords:
      spawnpoints:
        -263,66,308: -262.5,66,308.5,0.0,0.0,world
        -267,66,302: -266.5,66,302.5,0.0,0.0,world
        -275,66,302: -274.5,66,302.5,0.0,0.0,world
        -282,66,302: -281.5,66,302.5,0.0,0.0,world
        -285,66,308: -284.5,66,308.5,0.0,0.0,world
        -283,66,314: -282.5,66,314.5,0.0,0.0,world
        -275,66,314: -274.5,66,314.5,0.0,0.0,world
        -267,66,313: -266.5,66,313.5,0.0,0.0,world
      containers: {}
      p1: -288,65,298,0.0,0.0,world
      p2: -261,76,318,0.0,0.0,world
      lobby: -257.5,66,303.5,-270.61,0.0,world
      spectator: -286.5,73,310.5,-90.31,0.0,world
      arena: -270.5,66,308.5,91.79,0.0,world
      exit: -252.5,66,308.5,92.99,0.0,world
      l1: -260,65,298,0.0,0.0,world
      l2: -256,76,318,0.0,0.0,world
    class-limits:
      Archer: -1
      Oddjob: -1
      Chemist: -1
      Tank: -1
      Knight: -1
