# Dynmap-GriefPrevention configuration
update:
  period: 300
layer:
  name: 부동산
  hidebydefault: false
  layerprio: 0
  minzoom: 0
use3dregions: false
infowindow: '<div class=\"infowindow\">주인: <span style=\"font-weight:bold;\">%owner%</span><br/>권한
  제어 가능: <span style=\"font-weight:bold;\">%managers%</span><br/>건축 가능: <span style=\"font-weight:bold;\">%builders%</span><br/>상자
  접근 가능: <span style=\"font-weight:bold;\">%containers%</span><br/>접근 가능: <spanstyle=\"font-weight:bold;\">%accessors%</span></div>'
adminclaiminfowindow: '<div class=\"infowindow\"><span style=\"font-weight:bold;\">Administrator
  Claim</span><br/>Permission Trust: <span style=\"font-weight:bold;\">%managers%</span><br/>Trust:
  <span style=\"font-weight:bold;\">%builders%</span><br/>Container Trust: <span style=\"font-weight:bold;\">%containers%</span><br/>Access
  Trust: <span style=\"font-weight:bold;\">%accessors%</span></div>'
regionstyle:
  strokeColor: '#FF0000'
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: '#FF0000'
  fillOpacity: 0.35
visibleregions: []
hiddenregions: []
ownerstyle:
  administrator:
    strokeColor: '#0000FF'
    fillColor: '#0000FF'
