PopulationDensity:
  NewPlayersSpawnInHomeRegion: true
  RespawnInHomeRegion: true
  CityWorldName: ''
  AllowTeleportation: true
  TeleportFromAnywhere: false
  MaxDistanceFromSpawnToUseHomeRegion: 25
  ManagedWorldName: world
  DensityRatio: 1.0
  MaxIdleMinutes: 10
  LoginQueueEnabled: true
  MinimumPlayersOnlineForIdleBoot: 25
  ReservedSlotsForAdministrators: 1
  LoginQueueMessage: '%queuePosition% of %queueLength% in queue.  Reconnect within
    3 minutes to keep your place.  :)'
  HoursBetweenScans: 6
  BuildRegionPosts: true
  NewestRegionRequiresPermission: false
  GrassRegrows: true
  AnimalsRespawn: true
  TreesRegrow: true
  ThinOvercrowdedAnimalsAndMonsters: true
  MinimumRegionPostY: 62
  CustomSigns:
    Main:
    - ''
    - Population
    - Density
    - ''
    North:
    - ''
    - ''
    - ''
    - ''
    South:
    - ''
    - ''
    - ''
    - ''
    East:
    - ''
    - ''
    - ''
    - ''
    West:
    - ''
    - ''
    - ''
    - ''
