cfg-version: 10
message: '&c세상의 끝에 다다렀습니다. 더이상 나아갈 수 없습니다.'
round-border: true
debug-mode: false
whoosh-effect: false
knock-back-dist: 3.0
timer-delay-ticks: 5
dynmap-border-enabled: true
dynmap-border-message: 세상의 끝.
portal-redirection: true
remount-delay-ticks: 0
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list: []
fill-memory-tolerance: 500
worlds:
  world:
    x: 0.0
    z: 0.0
    radiusX: 2000
    radiusZ: 2000
    wrapping: false
  world_nether:
    x: 0.0
    z: 0.0
    radiusX: 250
    radiusZ: 250
    wrapping: false
  world_the_end:
    x: 0.0
    z: 0.0
    radiusX: 1500
    radiusZ: 1500
    wrapping: false
