update-events:
  - quit
serverID: 'semaul'
database:
  url: 'jdbc:mysql://localhost:3306/mydb?user=minecwotc&password=minecwotc'
  handler: 'tk.manf.InventorySQL.database.handler.MySQLDatabaseHandler'
data:
  serializer: 'tk.manf.InventorySQL.datahandling.serializer.SimpleSerializer'
  compressor: 'tk.manf.InventorySQL.datahandling.compressor.GZipCompressor'
enable-metrics: true
save-interval: 60
auto-update: true
