permissions:
  backend: sql
  backends:
    file:
      file: permissions.yml
    sql:
      uri: mysql://localhost/minecraft
      user: minecraft
      password: minecraft
      type: sql
  superperms: {}
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
multiserver:
  use-netevents: true
updater: true
alwaysUpdate: false
