# Global configuration for PurpleIRC
# How often we check to see if a bot is connected to the IRC server. This is in server ticks (There 20 ticks in one sec).
conn-check-interval: 1000
enable-ident-server: false
channel-check-interval: 100
message-format:
  console-chat: '&r[&5Server&r] %MESSAGE%'
  game-action: '&r***%NAME%&r %MESSAGE%'
  game-pchat: '&r<%NAME%&r> &r%MESSAGE%'
  game-pchat-response: ' &6-> &7%TARGET%: &r%MESSAGE%'
  game-chat: '&r<%NAME%&r> &r%MESSAGE%'
  game-death: '&r%MESSAGE%'
  game-kick: '&r%MESSAGE%'
  game-join: '&r%NAME% joined the game.'
  game-quit: '&r%NAME% left the game.'
  game-command: '&r Command detected by %NAME%: %COMMAND% %PARAMS%'
  game-send: '&r<%NAME%&r> &r%MESSAGE%'
  ess-player-afk: '&r %NAME% &ris now AFK'
  ess-player-not-afk: '&r %NAME% &ris no longer AFK'
  irc-action: '&r[&r#minec&r] ***%NAME%&r %MESSAGE%'
  irc-chat: '&r[&r#minec&r]<%NAME%&r> %MESSAGE%'
  irc-pchat: '&dPrivate message: &r[&r#minec&r]<%NAME%&r> %MESSAGE%'
  irc-pchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  irc-hchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  irc-join: '&r[&r#minec&r] %NAME%&r has joined %CHANNEL%.'
  irc-kick: '&r[&r#minec&r] %NAME%&r was kicked from %CHANNEL% by %KICKER%. (Reason-
    %REASON%)'
  irc-part: '&r[&r#minec&r] %NAME%&r has left %CHANNEL%.'
  irc-quit: '&r[&r#minec&r] %NAME%&r has left %CHANNEL%. (Reason: %REASON%)'
  irc-topic: '&r[&r#minec&r] Topic changed by %NAME%&r: %TOPIC%.'
  irc-nickchange: '&r[&r#minec&r] %OLDNICK% is now known as %NEWNICK%.'
  irc-mode: '&r[&r#minec&r] %NAME%&r %MODE% on %CHANNEL%'
  irc-notice: '&r[&r#minec&r] [notice(%CHANNEL%)] %NOTICE% '
  clever-send: '&r[&4BOT&r]<%NAME%&r> %MESSAGE%'
  mcmmo-admin-chat: '&r[admin:%WORLD%&r]<%NAME%&r> %MESSAGE%'
  mcmmo-party-chat: '&r[party:%PARTY%&r]<%NAME%&r> %MESSAGE%'
  faction-public-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'
  faction-ally-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'
  faction-enemy-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'
  hero-chat: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  hero-action: '&r[&2%CHANNEL%&r] ***%NAME%&r %MESSAGE%'
  irc-hero-action: '&r[&rIRC&r] ***%NAME%&r %MESSAGE%'
  irc-hero-chat: '&r[&rIRC&r]<%NAME%&r> %MESSAGE%'
  irc-hero-join: '&r[&rIRC&r] %NAME%&r has joined %CHANNEL%.'
  irc-hero-kick: '&r[&rIRC&r] %NAME%&r was kicked from %CHANNEL% by %KICKER%. (Reason-
    %REASON%)'
  irc-hero-part: '&r[&rIRC&r] %NAME%&r has left %CHANNEL%.'
  irc-hero-quit: '&r[&rIRC&r] %NAME%&r has left %CHANNEL%.'
  irc-hero-topic: '&r[&rIRC&r] Topic changed by %NAME%&r: %TOPIC%.'
  titan-chat: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  irc-titan-chat: '&r[&rIRC&r]<%NAME%&r> %MESSAGE%'
  invalid-irc-command: 
  no-perm-for-irc-command: 
  rts-notify: '[RTS] <%NAME%> %MESSAGE%'
  irc-hero-channels:
    Global: '&f[G]&f[IRC]%PLAYERPREFIX%%NAME%&f %MESSAGE%'
  broadcast-message: '[Broadcast] <%NAME%> %MESSAGE%'
  broadcast-console-message: '[Broadcast] <Console> %MESSAGE%'
  default-player-suffix: ''
  default-player-prefix: ''
  default-group-suffix: ''
  default-group-prefix: ''
  default-player-world: world
  default-player-group: ''
strip-game-colors: false
strip-irc-colors: false
custom-tab-list: false
custom-tab-prefix: '[IRC] '
nick-exact-match: true
Debug: false
