# Global configuration for PurpleIRC
# NOTE: If you make changes to this file while the server is running use "/irc reloadconfig" to load the changes into memory.
# How often we check to see if a bot is connected to the IRC server. This is in server ticks (There 20 ticks in one sec).
conn-check-interval: 1000
enable-ident-server: false
channel-check-interval: 100
message-format:
  console-chat: '&r[&5Server&r] %MESSAGE%'
  game-achievement: '[&2%WORLD%] %NAME% has just earned the achievement [%MESSAGE%]'
  game-mode: '[&2%WORLD%&r] %NAME% has changed game mode: [%MESSAGE%]'
  game-action: '&r***%NAME%&r %MESSAGE%'
  game-pchat: '&r<%NAME%&r> &r%MESSAGE%'
  death-messages: '[&2%WORLD%] %MESSAGE%'
  game-pchat-response: ' &6-> &7%TARGET%: &r%MESSAGE%'
  game-chat: '&r<%NAME%&r> &r%MESSAGE%'
  game-death: '&r%MESSAGE%'
  game-kick: '&r%MESSAGE%'
  game-join: '&r%NAME% joined the game.'
  game-quit: '&r%NAME% left the game.'
  game-command: '&r Command detected by %NAME%: %COMMAND% %PARAMS%'
  game-send: '&r<%NAME%&r> &r%MESSAGE%'
  ess-player-afk: '&r %NAME% &ris now AFK'
  ess-player-not-afk: '&r %NAME% &ris no longer AFK'
  ess-helpop: '&4[HelpOp] %DISPLAYNAME%&r: %MESSAGE%'
  irc-ess-helpop: '&4[HelpOp] %DISPLAYNAME%&r: %MESSAGE%'
  irc-action: '&r[&r#minec&r] ***%NAME%&r %MESSAGE%'
  irc-chat: '&r[&r#minec&r]<%NAME%&r> %MESSAGE%'
  irc-pchat: '&dPrivate message: &r[&r#minec&r]<%NAME%&r> %MESSAGE%'
  irc-pchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  irc-hchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  irc-join: '&r[&r#minec&r] %NAME%&r has joined %CHANNEL%.'
  irc-kick: '&r[&r#minec&r] %NAME%&r was kicked from %CHANNEL% by %KICKER%. (Reason-
    %REASON%)'
  irc-part: '&r[&r#minec&r] %NAME%&r has left %CHANNEL%.'
  irc-quit: '&r[&r#minec&r] %NAME%&r has left %CHANNEL%. (Reason: %REASON%)'
  irc-topic: '&r[&r#minec&r] Topic changed by %NAME%&r: %TOPIC%.'
  irc-nickchange: '&r[&r#minec&r] %OLDNICK% is now known as %NEWNICK%.'
  irc-mode: '&r[&r#minec&r] %NAME%&r %MODE% on %CHANNEL%'
  irc-console-chat: '&f[&5IRC&f]&r<%NAME%> %MESSAGE%'
  irc-notice: '&r[&r#minec&r] [notice(%CHANNEL%)] %NOTICE% '
  clever-send: '&r[&4BOT&r]<%NAME%&r> %MESSAGE%'
  mcmmo-admin-chat: '&r[admin:%WORLD%&r]<%NAME%&r> %MESSAGE%'
  mcmmo-party-chat: '&r[party:%PARTY%&r]<%NAME%&r> %MESSAGE%'
  mcmmo-chat: '&r[mcMMO]<%NAME%&r> %MESSAGE%'
  faction-public-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'
  faction-ally-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'
  faction-enemy-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'
  hero-chat: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  hero-action: '&r[&2%CHANNEL%&r] ***%NAME%&r %MESSAGE%'
  irc-hero-action: '&r[&rIRC&r] ***%NAME%&r %MESSAGE%'
  irc-hero-chat: '&r[&rIRC&r]<%NAME%&r> %MESSAGE%'
  irc-hero-join: '&r[&rIRC&r] %NAME%&r has joined %CHANNEL%.'
  irc-hero-kick: '&r[&rIRC&r] %NAME%&r was kicked from %CHANNEL% by %KICKER%. (Reason-
    %REASON%)'
  irc-hero-part: '&r[&rIRC&r] %NAME%&r has left %CHANNEL%.'
  irc-hero-quit: '&r[&rIRC&r] %NAME%&r has left %CHANNEL%.'
  irc-hero-topic: '&r[&rIRC&r] Topic changed by %NAME%&r: %TOPIC%.'
  titan-chat: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  irc-titan-chat: '&r[&rIRC&r]<%NAME%&r> %MESSAGE%'
  invalid-irc-command: I'm sorry '%NICK%' I can't do that. Type '%CMDPREFIX%help' for a list of commands I might respond to.
  no-perm-for-irc-command: I'm sorry '%NICK%' you are not authorized to do that. Type '%CMDPREFIX%help' for a list of commands I might respond to.
  rts-notify: '[RTS] <%NAME%> %MESSAGE%'
  rts-complete: '[RTS:Complete] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-claim: '[RTS:Claim] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-unclaim: '[RTS:Unclaim] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-held: '[RTS:Held] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-assign: '[RTS:Assign] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-reopen: '[RTS:Reopen] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  dynmap-web-chat: '[Dynmap] <%NAME%> %MESSAGE%'
  irc-dynmap-web-chat: '[IRC] %MESSAGE%'
  ore-broadcast: '[OreBroadcast] %MESSAGE%'
  jobs-separator: ', '
  irc-hero-channels:
    Global: '&f[G]&f[IRC]%PLAYERPREFIX%%NAME%&f %MESSAGE%'
  hero-channels:
    Global: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  hero-action-channels:
    Global: '&r[&2%CHANNEL%&r] ***%NAME%&r %MESSAGE%'
  towny-channel-chat: '&r%TOWNYCHANNELTAG%[%TOWNYCHANNEL%]<%NAME%&r> %MESSAGE%'
  irc-towny-chat: '[&3IRC]<%NAME%> %MESSAGE%'
  irc-towny-channels:
    irc: '[IRC]%PLAYERPREFIX%%NAME% %MESSAGE%'
  broadcast-message: '[Broadcast] <%NAME%> %MESSAGE%'
  broadcast-console-message: '[Broadcast] <Console> %MESSAGE%'
  prism-rollback: '[PrismRollback] [Player: %NAME%] [Radius: %RADIUS%] [Command: %COMMAND%]
    [Keyword: %KEYWORD%] [X,Y,Z: %X%,%Y%,%Z%] [World: %PARAMWORLD%]'
  prism-drain: '[PrismDrain] [Player: %NAME%] [Radius: %RADIUS%] [OrigBlock: %ORIGINALBLOCK%]
    [NewBlock: %NEWBLOCK%] [X,Y,Z: %X%,%Y%,%Z%] [World: %BLOCKWORLD%]'
  prism-extinguish: '[PrismExtinguish] [Player: %NAME%] [Radius%: %RADIUS] [OrigBlock:
    %ORIGINALBLOCK%] [NewBlock: %NEWBLOCK%] [X,Y,Z: %X%,%Y%,%Z%] [World: %BLOCKWORLD%]'
  prism-custom: '[PrismCustom] [Player: %NAME%] [Action: %ACTION%] [Message: %MESSAGE%]
    [Plugin: %PLUGIN%]'
  reddit-messages: '[R] %MESSAGE%'
  default-player-suffix: ''
  default-player-prefix: ''
  default-group-suffix: ''
  default-group-prefix: ''
  default-player-world: world
  default-player-group: ''
list-format: '&r[&9Minecraft&r] Online (%COUNT%/%MAX%): %PLAYERS%'
list-separator: '&r, '
list-player: '%GROUPPREFIX%%NAME%'
list-sort-by-name: true
strip-game-colors: false
strip-irc-colors: false
strip-irc-bg-colors: true
custom-tab-list: false
custom-tab-prefix: '[IRC] '
nick-exact-match: true
nick-prefixes:
  ircop: '&4~'
  ircsuperop: '&6&&'
  op: '&c@'
  halfop: '&3%'
  voice: '&2+'
irc-color-map:
  AQUA: CYAN
  BLACK: BLACK
  BLUE: BLUE
  BOLD: BOLD
  DARK_AQUA: TEAL
  DARK_BLUE: DARK_BLUE
  DARK_GRAY: DARK_GRAY
  DARK_GREEN: DARK_GREEN
  DARK_PURPLE: PURPLE
  DARK_RED: RED
  GOLD: OLIVE
  GRAY: LIGHT_GRAY
  GREEN: GREEN
  LIGHT_PURPLE: MAGENTA
  RED: RED
  UNDERLINE: UNDERLINE
  YELLOW: YELLOW
  WHITE: WHITE
  RESET: NORMAL
game-color-map:
  BLACK: BLACK
  BLUE: BLUE
  BOLD: BOLD
  BROWN: GRAY
  CYAN: AQUA
  DARK_BLUE: DARK_BLUE
  DARK_GRAY: DARK_GRAY
  DARK_GREEN: DARK_GREEN
  GREEN: GREEN
  LIGHT_GRAY: GRAY
  MAGENTA: LIGHT_PURPLE
  NORMAL: RESET
  OLIVE: GOLD
  PURPLE: DARK_PURPLE
  RED: RED
  TEAL: DARK_AQUA
  UNDERLINE: UNDERLINE
  WHITE: WHITE
  YELLOW: YELLOW
Debug: false
ignore-chat-cancel: false
