
# Give operators (set with the Minecraft /op command) all permissions.
op-permissions: true

# Use users' display names rather than than their raw username in various messages. Display names are set by other plugins.
use-display-names: true

# Similar to use-display-names, this allows usage of users' display names when looking up players.
lookup-with-display-names: true

# For /time, /weather, and other commands, broadcast change messages to everyone when you change world information with the commands.
broadcast-changes: true

# Disables some features to be compatible with badly-written server wrappers.
crappy-wrapper-compat: true

# When this setting is enabled, CommandBook's commands will be registered AFTER every 
# other plugin's commands. If any other plugin registers a command that conflicts with
# one of CommandBook's commands, the CommandBook command will be accessible with 
# /commandbook:<command>, and the other plugin's command will be accessible 
# with /<command>
low-priority-command-registration: false

# A list of enabled and disabled components. Components in the disabled list 
# will automatically be removed from the enabled list. Fully qualified class names can 
# or aliases (automatically added to the list by CommandBook) can be used as component names.
components:
    disabled:
    - help
    enabled:
    - bans
    - homes
    - warps
    - messaging
    - teleport
    - items
    - kits
    - midi
    - time
    - name-verification
    - fun
    - debug
    - thor
    - online-list
    - stored-messages
    - spawn-locations
    - info
    - world
    - player
    - god
    - flight
    - freeze

# Configurations for CommandBook's built-in components are stored here.
# Custom component configurations are stored as individual files in the the config/ folder
component:
    bans:
        message: You have been banned
        broadcast-bans: false
        broadcast-kicks: false
    homes:
        per-world: false
    warps:
        per-world: false
    messaging:
        console-say-format: <`r*Console`w> %s
        broadcast-format: '`r[Broadcast] %s'
        twitter-style: true
        pm-color: GRAY
        pm-text-color: RESET
    inventory:
        item-permissions-only: false
        allowed-items: []
        disllowed-items: []
        default-item-stack-size: 1
    time-control:
        time-lock:
        time-lock-delay: 20
    thor:
        hammer-items:
        - 257
        - 278
        - 270
        - 285
    online-list:
        show-max-players: true
        grouped-names: false
        colored-names: false
        list-on-join: true
    stored-messages:
        motd: |-
            안녕하세요, `Y%name%`w님.
            새마을에 오신것을 환영합니다.
            현재 시간은 `Y%time%`w 현재 위치는 `Y'%world%'`w입니다.
            새마을의 `b새소식이`w나 `b자세한 안내`w는 새마을 홈페이지 `bhttp://minec.wo.tc/`w를 참고해 주세요.
            만약 `r새마을 홈페이지에 가입이 안되어 있다면`w 곧장 `r서버 접속이 끊깁`w니다.
            그런 경우는 새마을 홈페이지에 가입 후 다시 접속해 주세요.
        rules: |-
            - `Y'근면'`w : 땀흘려 열심히 일하자.
            - `Y'자조'`w : 스스로 돕는 주민이 되자.
            - `Y'협동'`w : 함께 잘살자.
            새마을의 `b자세한 규칙`w은 새마을 홈페이지의 새마을 생활백서 `bhttp://minec.wo.tc/wiki`w를 참고해 주세요.
    spawn-locations:
        exact-spawn: false
    god:
        auto-enable: false
    teleports:
        call-message:
            sender: '`yTeleport request sent.'
            target: '`c**TELEPORT** %cname%`c requests a teleport! Use /bring <name>
                to accept.'
            too-soon: Wait a bit before asking again.
        bring-message:
            sender: '`yPlayer teleported.'
            target: '`yYour teleport request to %cname%`y was accepted.'
            no-perm: That person didn't request a teleport (recently) and you don't have permission to teleport anyone.
    flight:
        auto-enable: false
component-class-dirs:
- component-classes
component-jar-dirs:
- component-jars
